import pygame

#TELA
SPEED = 300 #NORMAL
TICK = 300 #QUANTO MAIOR, MAIS LENTO 
CLOCK = pygame.time.Clock().tick(TICK) / 1000
#JOGADOR
SCORE = 1
X_PLAYER = 370 # NORMAL
Y_PLAYER = 800#QUANTO MAIOR, O PERSONAGEM DESCE
X_PROJETIL = X_PLAYER-330
Y_PROJETIL = Y_PLAYER-50
ATIRAR = True
VELOCIDADE_PROJETIL = 100
if __name__=='__main__':
    ...